/**
 * Domain types. Split in two parts:
 *  1. Input model (what an importer produces / what the user edits)
 *  2. Analysis result (what the engine produces)
 * The engine depends on these types only – never on React.
 */

// ───────────────────────── Input model ─────────────────────────

export interface Column {
  name: string;
  /** Calculated column? Its DAX is analysed too (measures referenced there count as used). */
  calculated?: boolean;
  dax?: string;
  dataType?: string;
}

export interface Measure {
  name: string;
  dax: string;
  /** Optional free-text change info, e.g. "2024-05-01 by Jane" */
  lastModified?: string;
  description?: string;
  displayFolder?: string;
}

export interface Table {
  name: string;
  measures: Measure[];
  columns: Column[];
  /** DAX of a calculated table. Field parameters are calculated tables built from NAMEOF() references. */
  dax?: string;
}

export interface Visual {
  /** Stable id, generated by importer if missing */
  id: string;
  page: string;
  /** Stable page id (e.g. PBIR page folder name / report section name) – preferred for usage-metrics matching */
  pageId?: string;
  name: string;
  type: string;
  /** Measure references as written in the source: "[Revenue]", "Sales[Revenue]", "Revenue" … */
  measures: string[];
  /** Column references: "Sales[Amount]" … */
  columns: string[];
  /** Additional/unclassified field references. Resolved against the model (measure or column). */
  fields: string[];
}

/** Logical fields of a usage-metrics export. */
export type UsageField = 'report' | 'page' | 'pageId' | 'views' | 'uniqueUsers' | 'date';
/** logical field → header name of the imported file (by name, so it survives re-imports and persistence) */
export type UsageMapping = Partial<Record<UsageField, string>>;

/** One row of a usage-metrics export (page views of a report page, optionally per day). */
export interface UsageMetric {
  report?: string;
  page: string;
  pageId?: string;
  views: number;
  /** Unique users of that row. Never additive across rows/pages – see MeasureUsageMetrics.uniqueUsersPotential */
  uniqueUsers?: number;
  /** ISO date (YYYY-MM-DD) when parseable */
  date?: string;
}

export interface UsageImportMeta {
  id: string;
  fileName: string;
  format: 'csv' | 'xlsx' | 'xls';
  importedAt: string;
  mapping: UsageMapping;
  validRows: number;
  skippedRows: number;
}

export interface UsageMetricsMeta {
  imports: UsageImportMeta[];
  /** Restrict matching to one report of the file (display name); default: auto-detect from the model name */
  reportFilter?: string;
}

export interface ReportModel {
  name?: string;
  tables: Table[];
  visuals: Visual[];
  usageMetrics?: UsageMetric[];
  usageMeta?: UsageMetricsMeta;
}

// ───────────────────────── Analysis result ─────────────────────────

/** Unique measure id: "Table[Measure]" */
export type MeasureId = string;

/** Technical status */
export type UsageStatus = 'direct' | 'indirect' | 'unused';

export type VisualCategory = 'Card' | 'Table' | 'Matrix' | 'Chart' | 'Slicer' | 'KPI' | 'Other';

export interface ColumnRef {
  table: string;
  column: string;
}

export interface MeasureInfo {
  id: MeasureId;
  name: string;
  table: string;
  dax: string;
  lastModified?: string;
  description?: string;
  /** Measures referenced directly in DAX (resolved ids, de-duplicated) */
  dependsOn: MeasureId[];
  /** Measures whose DAX references this measure directly (any measure, used or not) */
  usedByMeasures: MeasureId[];
  /** Calculated columns ("Table[Col]") whose DAX references this measure */
  usedByColumns: string[];
  usedTables: string[];
  usedColumns: ColumnRef[];
  /** Transitive dependency count (all reachable measures, excluding itself unless cyclic) */
  transitiveDependencyCount: number;
  /** Longest chain of measures below this one (1 = leaf) */
  depth: number;
  inCycle: boolean;
  status: UsageStatus;
  isDirect: boolean;
  /** Referenced by at least one *used* measure (or used calculated column) */
  isIndirect: boolean;
  isUsed: boolean;
  /** Visual ids referencing the measure directly */
  directVisuals: string[];
  /** Visual ids reaching the measure via ≥1 measure hop */
  indirectVisuals: string[];
  /** Visuals that use a (used) field parameter containing this measure as selectable field */
  fieldParameterVisuals: string[];
  /** Ids of used field parameters that contain this measure */
  fieldParameters: string[];
  /** Union of direct, indirect and field-parameter visuals */
  allVisuals: string[];
  /** Number of *used* measures referencing this measure directly */
  indirectMeasureUsages: number;
  /** Shortest explanation path (see UsageReason). Null when unused. */
  reason: UsageReason | null;
}

export interface UsageReason {
  /**
   * Root that keeps the chain alive. For `fieldParameter` the visual uses a field parameter table
   * (Page → Visual → Field Parameter → Measure …); the value is the field-parameter id.
   */
  root: { kind: 'visual'; visualId: string; fieldParameter?: string } | { kind: 'column'; column: string };
  /** Measure chain from the first measure used by the root down to the target (inclusive) */
  chain: MeasureId[];
}

export interface VisualInfo {
  id: string;
  page: string;
  pageId?: string;
  name: string;
  type: string;
  category: VisualCategory;
  /** Resolved measure ids used directly */
  measures: MeasureId[];
  columns: ColumnRef[];
  /** Raw references we could not resolve against the model */
  unresolved: string[];
  /** Field parameters (ids) whose table this visual uses */
  fieldParameters: string[];
  /** All measures reachable from this visual (direct + field-parameter members + their dependencies) */
  reachableMeasures: MeasureId[];
}

/** A calculated table that lists fields via NAMEOF(), i.e. a Power BI field parameter. */
export interface FieldParameterInfo {
  /** "fp:<table>" */
  id: string;
  table: string;
  /** Display name = table name */
  name: string;
  dax: string;
  /** Measures referenced through NAMEOF (resolved, de-duplicated) */
  measures: MeasureId[];
  /** Columns referenced through NAMEOF (parameters may also switch columns) */
  columns: ColumnRef[];
  usedByVisuals: string[];
  /** true only when at least one visual uses the parameter – mere existence keeps nothing alive */
  isUsed: boolean;
}

export interface TableInfo {
  name: string;
  isFieldParameter: boolean;
  measureIds: MeasureId[];
  columns: Column[];
  unusedMeasureCount: number;
}

export interface CycleInfo {
  /** e.g. [A, B, C] meaning A → B → C → A */
  path: MeasureId[];
  /** All members of the strongly connected component */
  members: MeasureId[];
}

export interface DependencyChain {
  /** From the top measure down to the deepest dependency */
  path: MeasureId[];
  /** True when the chain ends inside a circular dependency */
  endsInCycle: boolean;
}

export interface ColumnUsage {
  table: string;
  column: string;
  measures: MeasureId[];
  visuals: string[];
}

export interface AnalysisWarning {
  kind: 'ambiguous-measure' | 'unresolved-visual-field' | 'duplicate-measure' | 'unknown-table';
  message: string;
}

// ───────────────────────── Usage metrics analysis ─────────────────────────

/** Observed-usage class, separate from the technical status (direct / indirect / unused). */
export type UsageLevel = 'HIGH' | 'MEDIUM' | 'LOW' | 'NO_OBSERVED_USAGE' | 'NO_USAGE_DATA';

/**
 * Estimated reach of a measure derived from page views and the technical page → visual → measure mapping.
 * NOT the number of DAX executions or field-parameter selections.
 */
export interface MeasureUsageMetrics {
  measureId: MeasureId;
  usageStatus: UsageLevel;
  /** Visuals referencing the measure directly (every visual counts) */
  directVisualCount: number;
  /** Visuals reaching the measure through ≥1 other measure (visual paths) */
  indirectVisualCount: number;
  /** Visuals offering the measure as selectable field of a used field parameter */
  fieldParameterVisualCount: number;
  /** Views of all distinct matched pages where the measure is technically reachable (each page counted once) */
  pageViewsPotential: number;
  /** Views of pages where a visual references the measure directly */
  directPageViewsPotential: number;
  /** Views of pages where the measure is reachable ONLY through measure dependencies */
  indirectPageViewsPotential: number;
  /** Views of pages where the measure is selectable through a field parameter (candidate, not actual selection) */
  parameterCandidateViews: number;
  /** Non-deduplicated sum of the unique-user numbers of the distinct pages. Not an organisation-wide unique count. */
  uniqueUsersPotential?: number;
  /** Display names of distinct pages that are reachable AND have usage rows */
  matchedPages: string[];
}

export interface PageUsage {
  page: string;
  pageId?: string;
  views: number;
  /** Sum over rows – not de-duplicated (no user ids available) */
  uniqueUsers?: number;
  rows: number;
  dates: string[];
}

export type UnmatchedReason = 'page-not-found' | 'ambiguous-page' | 'other-report';

export interface UnmatchedUsage {
  report?: string;
  page: string;
  views: number;
  rows: number;
  reason: UnmatchedReason;
}

export interface UsageAnalysis {
  hasData: boolean;
  totalViews: number;
  matchedViews: number;
  unmatchedViews: number;
  pages: PageUsage[];
  unmatched: UnmatchedUsage[];
  /** Model pages without any usage row */
  pagesWithoutUsage: string[];
  availableReports: string[];
  /** Report the matching was restricted to (if any) */
  activeReport?: string;
  measures: Map<MeasureId, MeasureUsageMetrics>;
  /** visual id → views of its page */
  visualPageViews: Map<string, number>;
  distribution: { measuresWithViews: number; min: number; median: number; max: number };
}

export interface AnalysisSummary {
  totalMeasures: number;
  usedMeasures: number;
  directMeasures: number;
  indirectMeasures: number;
  unusedMeasures: number;
  dependencies: number;
  tables: number;
  visuals: number;
  pages: number;
  cycles: number;
  fieldParameters: number;
  usedFieldParameters: number;
}

export interface AnalysisResult {
  measures: Map<MeasureId, MeasureInfo>;
  measureOrder: MeasureId[];
  visuals: Map<string, VisualInfo>;
  tables: Map<string, TableInfo>;
  pages: string[];
  fieldParameters: Map<string, FieldParameterInfo>;
  usage: UsageAnalysis;
  cycles: CycleInfo[];
  longestChains: DependencyChain[];
  columnUsage: ColumnUsage[];
  warnings: AnalysisWarning[];
  summary: AnalysisSummary;
}
