/**
 * Domain types. Split in two parts:
 *  1. Input model (what an importer produces / what the user edits)
 *  2. Analysis result (what the engine produces)
 * The engine depends on these types only – never on React.
 */

// ───────────────────────── Input model ─────────────────────────

export interface Column {
  name: string;
  /** Calculated column? Its DAX is analysed too (measures referenced there count as used). */
  calculated?: boolean;
  dax?: string;
  dataType?: string;
}

export interface Measure {
  name: string;
  dax: string;
  /** Optional free-text change info, e.g. "2024-05-01 by Jane" */
  lastModified?: string;
  description?: string;
  displayFolder?: string;
}

export interface Table {
  name: string;
  measures: Measure[];
  columns: Column[];
}

export interface Visual {
  /** Stable id, generated by importer if missing */
  id: string;
  page: string;
  name: string;
  type: string;
  /** Measure references as written in the source: "[Revenue]", "Sales[Revenue]", "Revenue" … */
  measures: string[];
  /** Column references: "Sales[Amount]" … */
  columns: string[];
  /** Additional/unclassified field references. Resolved against the model (measure or column). */
  fields: string[];
}

export interface ReportModel {
  name?: string;
  tables: Table[];
  visuals: Visual[];
}

// ───────────────────────── Analysis result ─────────────────────────

/** Unique measure id: "Table[Measure]" */
export type MeasureId = string;

export type UsageStatus = 'direct' | 'indirect' | 'unused';

export type VisualCategory = 'Card' | 'Table' | 'Matrix' | 'Chart' | 'Slicer' | 'KPI' | 'Other';

export interface ColumnRef {
  table: string;
  column: string;
}

export interface MeasureInfo {
  id: MeasureId;
  name: string;
  table: string;
  dax: string;
  lastModified?: string;
  description?: string;
  /** Measures referenced directly in DAX (resolved ids, de-duplicated) */
  dependsOn: MeasureId[];
  /** Measures whose DAX references this measure directly (any measure, used or not) */
  usedByMeasures: MeasureId[];
  /** Calculated columns ("Table[Col]") whose DAX references this measure */
  usedByColumns: string[];
  usedTables: string[];
  usedColumns: ColumnRef[];
  /** Transitive dependency count (all reachable measures, excluding itself unless cyclic) */
  transitiveDependencyCount: number;
  /** Longest chain of measures below this one (1 = leaf) */
  depth: number;
  inCycle: boolean;
  status: UsageStatus;
  isDirect: boolean;
  /** Referenced by at least one *used* measure (or used calculated column) */
  isIndirect: boolean;
  isUsed: boolean;
  /** Visual ids referencing the measure directly */
  directVisuals: string[];
  /** Visual ids reaching the measure via ≥1 measure hop */
  indirectVisuals: string[];
  /** Union of both */
  allVisuals: string[];
  /** Number of *used* measures referencing this measure directly */
  indirectMeasureUsages: number;
  /** Shortest explanation path (see UsageReason). Null when unused. */
  reason: UsageReason | null;
}

export interface UsageReason {
  /** Root that keeps the chain alive */
  root: { kind: 'visual'; visualId: string } | { kind: 'column'; column: string };
  /** Measure chain from the first measure used by the root down to the target (inclusive) */
  chain: MeasureId[];
}

export interface VisualInfo {
  id: string;
  page: string;
  name: string;
  type: string;
  category: VisualCategory;
  /** Resolved measure ids used directly */
  measures: MeasureId[];
  columns: ColumnRef[];
  /** Raw references we could not resolve against the model */
  unresolved: string[];
  /** All measures reachable from this visual (direct + indirect) */
  reachableMeasures: MeasureId[];
}

export interface TableInfo {
  name: string;
  measureIds: MeasureId[];
  columns: Column[];
  unusedMeasureCount: number;
}

export interface CycleInfo {
  /** e.g. [A, B, C] meaning A → B → C → A */
  path: MeasureId[];
  /** All members of the strongly connected component */
  members: MeasureId[];
}

export interface DependencyChain {
  /** From the top measure down to the deepest dependency */
  path: MeasureId[];
  /** True when the chain ends inside a circular dependency */
  endsInCycle: boolean;
}

export interface ColumnUsage {
  table: string;
  column: string;
  measures: MeasureId[];
  visuals: string[];
}

export interface AnalysisWarning {
  kind: 'ambiguous-measure' | 'unresolved-visual-field' | 'duplicate-measure' | 'unknown-table';
  message: string;
}

export interface AnalysisSummary {
  totalMeasures: number;
  usedMeasures: number;
  directMeasures: number;
  indirectMeasures: number;
  unusedMeasures: number;
  dependencies: number;
  tables: number;
  visuals: number;
  pages: number;
  cycles: number;
}

export interface AnalysisResult {
  measures: Map<MeasureId, MeasureInfo>;
  measureOrder: MeasureId[];
  visuals: Map<string, VisualInfo>;
  tables: Map<string, TableInfo>;
  pages: string[];
  cycles: CycleInfo[];
  longestChains: DependencyChain[];
  columnUsage: ColumnUsage[];
  warnings: AnalysisWarning[];
  summary: AnalysisSummary;
}
